image: adrasteondev/godot-ci:mono-4.1



build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - dotnet --version
    # /usr/share/dotnet is failing
    # - /usr/share/dotnet --version
    - dotnet restore
    - dotnet run 

