name: "godot-ci test"
on: push

jobs:
  test-dotnet:
    name: Test Dotnet
    runs-on: ubuntu-22.04
    container:
      image: adrasteondev/godot-ci:mono-4.1
    steps:
      - name: Check Version
        run: |
            dotnet --version
